# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeRouterProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeRouterProject

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
    ]

    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"


   pod 'RSKImageCropper'
   pod 'QBImagePickerController'

  target 'NativeRouterProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeRouterProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

